# Generated by Django 5.1.1 on 2024-10-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
